######################################################################
# Automatically generated by qmake (3.0) Mon Nov 20 11:45:08 2017
######################################################################

TEMPLATE = app

QT+=gui widgets
SOURCES=main.cpp

LIBS+=-L../src/ -lqjenkins
INCLUDEPATH +=../src

# Directories
