######################################################################
# Automatically generated by qmake (3.0) Mon Nov 20 11:44:30 2017
######################################################################

TEMPLATE = subdirs

SUBDIRS= src example

# Directories
