######################################################################
# Automatically generated by qmake (3.0) Mon Nov 20 11:45:03 2017
######################################################################

TEMPLATE =lib
TARGET=qjenkins

QT +=network

# Directories

HEADERS += \
    qjenkins.h \
    jenkinsimpl.h

SOURCES += \
    qjenkins.cpp \
    jenkinsimpl.cpp
